### ISSUE TITLE
FreshWaterModule

### ISSUE THREAD

**Issue by mleck28** [LavermanJJ/home-assistant-solarfocus#104]
Hello, 
it seems that a conversion is missing in the freshwater module. For the temperatures (see image), it's likely that there needs to be a division by '10'.

![HA_SolarFocus_FreshWaterModule](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/160210695/fcd6c903-802c-40b3-b30e-fee7be9be736)

**Comment by LavermanJJ** [comment]
Hi @mleck28 - this is already fixed in the latest beta. Thanks for the reminder to release it 👍

**Comment by LavermanJJ** [comment]
Fix is released in 4.2.0.1
