### ISSUE TITLE
Fehler Umschalten Modus

### ISSUE THREAD

**Issue by Dengo91** [LavermanJJ/home-assistant-solarfocus#107]
Hallo, ich habe die Intigartion installiert und leider geht das umschalten der Moduse nicht (Siehe Bild / Hier wird unten auch der Fehler angezeigt.).
![1](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/171798362/23a75680-521a-4734-85e0-195f08fdeba5)

**Desktop (please complete the following information):**
 - Home assistant version: 2024.6.2
 - Solarfocus firmware version: V22.020

**Comment by Dengo91** [comment]
Ich sehe noch 2 weitere Fehler im Protokoll von Home Assistant:

Logger: root
Quelle: /usr/local/lib/python3.12/site-packages/pysolarfocus/components/base/component.py:161
Erstmals aufgetreten: 11:24:58 (1401 Vorkommnisse)
Zuletzt protokolliert: 14:33:51

Failed to read holding registers of Buffer
_____________________________________________________________________________________________

Logger: root
Quelle: /usr/local/lib/python3.12/site-packages/pysolarfocus/modbus_wrapper.py:65
Erstmals aufgetreten: 11:24:58 (1401 Vorkommnisse)
Zuletzt protokolliert: 14:33:51

Modbus read error at address=34000: Exception Response(131, 3, IllegalAddress)

**Comment by Dengo91** [comment]
Evtl hilft das ja noch. Könnten die Probleme an meiner Solarfocus Firmware-Version: V22.020 liegen?

**Comment by LavermanJJ** [comment]
Fixed in 4.3.0 👍
