### ISSUE TITLE
Missing english translation key for host

### ISSUE THREAD

**Issue by LLukas22** [LavermanJJ/home-assistant-solarfocus#16]
![image](https://user-images.githubusercontent.com/65088241/196390810-2a004dae-deed-42e5-bc49-074e945bbf39.png)

The translation key for the *host* field is missing or has a typo.

**Comment by LavermanJJ** [comment]
Fixed in https://github.com/LavermanJJ/home-assistant-solarfocus/releases/tag/v1.2.0-beta-10
