### ISSUE TITLE
Support multiple heating circuits, buffers, and boilers

### ISSUE THREAD

**Issue by LavermanJJ** [LavermanJJ/home-assistant-solarfocus#17]
Up to now, this integration only supports 1 heating circuit, however, Solarfocus supports up to 8 circuits. The pysolarfocus library and this integration should be extended to support multiple heating circuits.

**Comment by bszattila** [comment]
Is  there any timeplan when all heating circuits will be implemented?

**Comment by LavermanJJ** [comment]
The extension of the library has been merged yesterday and I startet to extend the HA integration. Hope this will be done within a week, but obviously no commitment.

**Comment by bszattila** [comment]
Cross fingers for You! Can i buy You a coffe or a beer? :D

**Comment by LavermanJJ** [comment]
@bszattila much appreciated your asking, however, I currently have neither. 🙈

**Comment by LavermanJJ** [comment]
A release candidate is available for testing

**Comment by Vaszago** [comment]
@LavermanJJ 
Thank you for providing the additional heating circuits so quickly. These also work right away. The one problem is worth the COP. HA writes me an error in the formula. I've tried a few things but haven't found a solution yet.
Can you please take a look at it.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/66181893/199312612-07169f54-a2d7-435a-99bd-7bce0906593b.png">


Thanks

**Comment by LavermanJJ** [comment]
Thanks. The issue is in the second last line at the end with '0.0' which is the default value. If you change it to 1.0 it should work.

In Addition you should check, if the sensors are the correct ones I.e., the entity ID is correct.

Ps: I'll adapt it in the release notes as well. Thanks for pointing this out
