### ISSUE TITLE
Unfortunately, I still get an error when I want to query the COP value.

### ISSUE THREAD

**Issue by Vaszago** [LavermanJJ/home-assistant-solarfocus#26]
Unfortunately, I still get an error when I want to query the COP value.

![image](https://user-images.githubusercontent.com/66181893/199896716-273875bc-5f1f-451f-90ed-a62e4bc02936.png)

Here is the entry in Yaml

![image](https://user-images.githubusercontent.com/66181893/199897176-d8248c9c-7049-441a-b22b-d81fb3c05e37.png)

But the code works under template

![image](https://user-images.githubusercontent.com/66181893/199897367-39b65065-8cb2-497d-b6b5-f3ff401159b1.png)

What am I doing wrong

_Originally posted by @Vaszago in https://github.com/LavermanJJ/home-assistant-solarfocus/issues/15#issuecomment-1302996779_

**Comment by LavermanJJ** [comment]
I'm still investigating myself. I'll let you know one if fixed it.

**Comment by LavermanJJ** [comment]
I've extended it a little bit, to check for `0.0` values to avoid division by zero. However, your error message seems to be related to the overall structure: `sensor` -> `template` -> `sensors` -> `solarfocus_heat_pump_cop`

Below is the structure of my config:
```
sensor:
  - platform: template
    sensors:
      solarfocus_heat_pump_cop:
        friendly_name: "COP"
        unit_of_measurement: "W/W"
        icon_template: mdi:poll
        value_template: >
          {% if states("sensor.solarfocus_heat_pump_electrical_power") | int == 0 %}
          0.0
          {% else %}
          {{ '%0.f' | format(float(states('sensor.solarfocus_heat_pump_heating_thermal_power'), 0.0)  / 
              float(states('sensor.solarfocus_heat_pump_electrical_power'), 0.0)
          ) }}
          {%endif%}
```

**Comment by LavermanJJ** [comment]
I decided to re-introduce the COP calculation to the library and make it more specific:
* cop heating
* cop drinking water
* overall performance number heating
* overall performance number drinking water

The only thing that has to be done within HA (due to the missing persistence of the library itself), is the calculation of the _Jahresarbeitszahl_ (JAZ, annual performance number). I'll close this issue, as soon as the release is out.

**Comment by Vaszago** [comment]
Hi
I had to adjust the code a bit. My query now works correctly.



That would be great if you could tie it in like this.


Gesendet von Mail für Windows

Von: Jeroen Laverman
Gesendet: Montag, 7. November 2022 08:02
An: LavermanJJ/home-assistant-solarfocus
Cc: Vaszago; Mention
Betreff: Re: [LavermanJJ/home-assistant-solarfocus] Unfortunately, I still getan error when I want to query the COP value. (Issue #26)

I decided to re-introduce the COP calculation to the library and make it more specific:
• cop heating
• cop drinking water
• overall performance number heating
• overall performance number drinking water
The only thing that has to be done within HA (due to the missing persistence of the library itself), is the calculation of the Jahresarbeitszahl (JAZ, annual performance number). I'll close this issue, as soon as the release is out.

**Comment by Vaszago** [comment]
Hi
I had to adjust the code a bit. My query now works correctly.

 
![image](https://user-images.githubusercontent.com/66181893/200247653-f139b086-812a-4337-8567-1c66bff22465.png)


That would be great if you could tie it in like this.

**Comment by Vaszago** [comment]
It would be cool if you could also include the outside temperature of the WP in your query. Then I could delete the manual query via Modbus.

![image](https://user-images.githubusercontent.com/66181893/200250139-b6b70023-2d5f-4e19-aabc-9d487153577c.png)

**Comment by LavermanJJ** [comment]
@Vaszago please create a new issue for that. Thanks

**Comment by LavermanJJ** [comment]
@Vaszago COP is now available again. The `cop_heating` corresponds to the former coefficient of performance provided by the integration.
