### ISSUE TITLE
Solar don't work. State just a number

### ISSUE THREAD

**Issue by saschaguilliard** [LavermanJJ/home-assistant-solarfocus#27]
I don't know what is wrong
![image](https://user-images.githubusercontent.com/115590293/200167786-d808d3c6-4fa6-4e7b-86c6-939af61f6a69.png)
![image](https://user-images.githubusercontent.com/115590293/200167804-ab680fc3-dac0-4f37-8f5e-0ad310d6baf5.png)
![image](https://user-images.githubusercontent.com/115590293/200167827-6885ec20-8696-4124-a423-bf407357aede.png)

in your exe all sensors are ok. In your release everythyíng is 0

And the second Problem:
All States are a Number. No Text like "Bereitschaft" 

Edit:
In Version 2.0.0 State is correct
![image](https://user-images.githubusercontent.com/115590293/200168168-a1f73c08-c861-4c35-955d-b35158848eb7.png)

**Comment by LavermanJJ** [comment]
Regarding the state numbers you can try clearing the cache of your browser. 

Regarding the missing values, is there any message / details in your home assistant logs?

**Comment by LavermanJJ** [comment]
Did you remove and add the integration to see if that fixes it?

**Comment by saschaguilliard** [comment]
Yes, removed and new added.
state numbers is fine...
Solar is everything 0°C

**Comment by LavermanJJ** [comment]
I've found the issue. Forgot to extend the coordinator to update the values 🙈 
I'll provide a fix.

**Comment by LavermanJJ** [comment]
@saschaguilliard does it work now?

**Comment by saschaguilliard** [comment]
Yes, very good job.
