### ISSUE TITLE
Read out the remaining, still missing values from Modbus

### ISSUE THREAD

**Issue by Vaszago** [LavermanJJ/home-assistant-solarfocus#32]
Such as the outside temperature of the heat pump, external room temperature, etc. There is some certainly more.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/66181893/200354923-e866695c-a20a-4479-b344-fcc1189b4aee.png">

With this I could remove the normal Modbus query from HA.

**Comment by Vaszago** [comment]
I had also been looking for a long time but that is the outside temperature of the heat pump.
Unfortunately, I cannot tell you why it is the same address as the boiler. But it works.

<img width="506" alt="image" src="https://user-images.githubusercontent.com/66181893/200390658-decb78d8-4435-4c62-8381-ca66e17d1219.png">

**Comment by LLukas22** [comment]
@Vaszago Alright can you try to add the boiler in the setup and check if the values match?

**Comment by Vaszago** [comment]
Unfortunately I don't know how to include this entry in the setup!

**Comment by LavermanJJ** [comment]
Currently, it is not possible I guess, as heat pump and bio mass boiler are exclusive, as currently implemented in the integration.

You would need to add another instance of the integration and configure it to only Bio mass boiler.

**Comment by LavermanJJ** [comment]
I've just checked. We would need to adapt the register layout for vampair for bio mass boiler.

I'll look at it later.

**Comment by LavermanJJ** [comment]
It actually seems to work already.
Is the precision the same for you ie, no 10th degree or so?

![image](https://user-images.githubusercontent.com/12856211/201062093-507fae68-3911-4439-9329-ca310359b832.jpeg)

**Comment by PhilippRettenmeier** [comment]
Also posdible to add the modbus features fir circulation pump? Adress e.g. 32003

**Comment by LavermanJJ** [comment]
> Also posdible to add the modbus features fir circulation pump? Adress e.g. 32003

That is already available when the Boiler component is enabled. There is a button to trigger the circulation (`button.solarfocus_boiler_1_circulation`) and a sensor for reading the current state of the circulation (`sensor.solarfocus_boiler_1_circulation`)

**Comment by PhilippRettenmeier** [comment]
Oh, Thanks, did not recognize this.
Now I can check that, Thank you :)

**Comment by bszattila** [comment]
> button.solarfocus_boiler_1_circulation

Is there also possibility to start stop the heating circulator pumps? i see only the binary sensor to check the state. and when i change heat mode, it fdoes not stop the circulator pumps...

**Comment by LavermanJJ** [comment]
> > button.solarfocus_boiler_1_circulation
> 
> 
> 
> Is there also possibility to start stop the heating circulator pumps? i see only the binary sensor to check the state. and when i change heat mode, it fdoes not stop the circulator pumps...

@bszattila Unfortunately, there is no control provided by Solarfocus currently. However, for me the behavior is as expected from you: if I turn of the heating the circulation pump of the heating also stops. So maybe contact the Solarfocus support why this is the case in your installation?

**Comment by PhilippRettenmeier** [comment]
> > > > button.solarfocus_boiler_1_circulation
> > > 
> > > 
> > > Is there also possibility to start stop the heating circulator pumps? i see only the binary sensor to check the state. and when i change heat mode, it fdoes not stop the circulator pumps...
> > 
> > 
> > @bszattila Unfortunately, there is no control provided by Solarfocus currently. However, for me the behavior is as expected from you: if I turn of the heating the circulation pump of the heating also stops. So maybe contact the Solarfocus support why this is the case in your installation?
> 
> Thank you! I contacted them, let's see what their answer ;) i share if it is modbus related, and not my pellet broken

Really strange - tried the button "request circulation" as well which works. However, not possible to stop the circulation pump viy TCP / Modbus.

That would be such a great, energy saving feature (e.g. for triggering the circulation via smart switch in bathroon and stop it after 30s).

I'll contact Solarfocus as well...

**Comment by bszattila** [comment]
> > > > > button.solarfocus_boiler_1_circulation
> > > > 
> > > > 
> > > > Is there also possibility to start stop the heating circulator pumps? i see only the binary sensor to check the state. and when i change heat mode, it fdoes not stop the circulator pumps...
> > > 
> > > 
> > > @bszattila Unfortunately, there is no control provided by Solarfocus currently. However, for me the behavior is as expected from you: if I turn of the heating the circulation pump of the heating also stops. So maybe contact the Solarfocus support why this is the case in your installation?
> > 
> > 
> > Thank you! I contacted them, let's see what their answer ;) i share if it is modbus related, and not my pellet broken
> 
> Really strange - tried the button "request circulation" as well which works. However, not possible to stop the circulation pump viy TCP / Modbus.
> 
> That would be such a great, energy saving feature (e.g. for triggering the circulation via smart switch in bathroon and stop it after 30s).
> 
> I'll contact Solarfocus as well...

O, i already got feedback on my enquiry. They are saying: 
that’s because the outside temperature is low, the frost protection mode is active.

If the outside temperature drops under this parameter the pump will run 24h.

If you decrease this parameter to minus temperatures it will switch off (attached a picture where You can setup the antifreeze temperature, which in our case is set to 5 degrees)

But in the worst case some heating water pipes can freeze if nobody watch the system and the boiler is switched off or has a fault.

**Comment by LavermanJJ** [comment]
Good Point - so checking heating state makes sense in addition. This sensor will show if e.g. frost protection is active.

**Comment by PhilippRettenmeier** [comment]
> It actually seems to work already. Is the precision the same for you ie, no 10th degree or so?
> 
> ![image](https://user-images.githubusercontent.com/12856211/201062093-507fae68-3911-4439-9329-ca310359b832.jpeg)

Is the outside temperature already integrated as sensor when installing the Integration? I cannot see it when Integrating the vampair with boiler... otherwise, one can use the integration in config.yaml from vaszago

**Comment by bszattila** [comment]
> Good Point - so checking heating state makes sense in addition. This sensor will show if e.g. frost protection is active.

I am recording the heating state on a graph, and i observed that it returns different values. is there any reason for it? sometimes it returns value 5,8,12, 17 and 0 of course, when heating stops. Do You know what is the difference between the values?

**Comment by bszattila** [comment]
i made the update, and now i have this issue: %key:common::config_flow::error::cannot_connect%]

**Comment by LavermanJJ** [comment]
@bszattila the numbers refer to the Enumeration from the [Specification](https://www.solarfocus.com/de/partnerportal/pdf/open/UGFydG5lcmJlcmVpY2gtREUvUmVnZWx1bmdfZWNvbWFuYWdlci10b3VjaC9BbmxlaXR1bmdlbi9lY29tYW5hZ2VyLXRvdWNoX01vZGJ1cy1UQ1AtUmVnaXN0ZXJkYXRlbl9BbmxlaXR1bmcucGRm/117920/0/Lng_YSxpM245S30zMTc4W2Y8cVRRXWlJVWRQJDsv?serialNumber=21010) cf. `Status Heizkreis`

**Comment by LavermanJJ** [comment]
@PhilippRettenmeier yes, the outdoor temperature sensor of the Vampair seems to be available as sensor of the Biomass Boiler. Therefore, to make use of this sensor, you need to add the Solarfocus integration twice: 
1. Configured as VampAir heat pump + the respective components
2. Configured as Biomass Boiler Therminator. <-- afterwards you can delete all sensors but the outdoor temperature, as the other sensor values are invalid. Make sure you name the second instance differently

<img width="293" alt="image" src="https://user-images.githubusercontent.com/12856211/208242691-89ba2f74-481c-4f06-930b-e00022206cb1.png">

**Comment by PhilippRettenmeier** [comment]
Great, works, thanks a lot
