### ISSUE TITLE
Support Software 22.100

### ISSUE THREAD

**Issue by PhilippRettenmeier** [LavermanJJ/home-assistant-solarfocus#33]
Possible to integrate support of Solarfocus Software V22.100?

And define heating circuit supply temp. in relation to outside temperature, i.e. heating curve?

**Comment by LavermanJJ** [comment]
@PhilippRettenmeier Do you have the specification at hand so I can have a look what we would need to adapt?

**Comment by PhilippRettenmeier** [comment]
[TCP Doc](https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.solarfocus.com/produkte/Waermepumpe/EcoManager-t_Modbus-TCP-Registerdaten_Anleitung.pdf&ved=2ahUKEwi_-oTV0rr7AhU9g_0HHc-RDB8QFnoECBMQAQ&usg=AOvVaw1K-hvxACdjmI3JMwnrVFcG) 

TCP doc see link. As far as I see, it is not possible to set heating curve vy TCP, sorry.

New Software doc is not available as far as I know...

**Comment by LavermanJJ** [comment]
Ok - then I'll close the issue. 👍
