### ISSUE TITLE
State names missing after HA 2023.04 update

### ISSUE THREAD

**Issue by LavermanJJ** [LavermanJJ/home-assistant-solarfocus#34]
![image](https://user-images.githubusercontent.com/12856211/230614014-c5f3f24a-a84e-4a00-8d8c-06598e1f689b.jpeg)

After updating to 2023.04 the states are no longer translated but the plain numbers are shown.

**Comment by lein1013** [comment]
Could this be related to 
https://github.com/home-assistant/core/commit/8968ed1c47314db4b9ee7eeb302c92c4e71915a3

? 
based on NON_NUMERIC_DEVICE_CLASSES
https://github.com/home-assistant/core/blob/6c7f2167ff0bea90a26cbb08035a8e16a2478acc/homeassistant/components/sensor/const.py#L406

not sure how uptodate the documentation is but according to
https://developers.home-assistant.io/docs/core/entity/sensor

based on that I would expect that 
```
    SensorEntityDescription(
        key="vampair_state",
        icon="mdi:heat-pump",
        device_class="solarfocus__hpstate",
    ),
```
must be somehow changed to something like
```
    SensorEntityDescription(
        key="vampair_state",
        icon="mdi:heat-pump",
        device_class=SensorDeviceClass.ENUM,
       state_class=StateClass.MEASUREMENT,
        options={
             "0": "Bereitschaft",
      "1": "Heizbetrieb",
...
        },
    ),
```
Not sure if this should be a dict or a list (base on the doc), and if its `opitions` or `state`
I wanted to update today, but I think I will now postpone :-)

**Comment by LavermanJJ** [comment]
Looks like it. Somehow missed that change 😇 try to fix this asap
