### ISSUE TITLE
Add English translations for pellets boiler

### ISSUE THREAD

**Issue by LavermanJJ** [LavermanJJ/home-assistant-solarfocus#38]
Translate the following states:

https://github.com/LavermanJJ/home-assistant-solarfocus/blob/f9d98696988763ac55422e49f9341dbe8de962d2/custom_components/solarfocus/translations/en.json#L105-L193

**Comment by tinerop** [comment]
Here is the English translation for the boiler. I sourced it directly from the original Solarfocus document "DR-0180-EN / v9-202202" page 8, available from [https://www.solarfocus.com/en/partnerportal/pdf/open/UGFydG5lcmJlcmVpY2gtRU4vUmVnZWx1bmdfZWNvbWFuYWdlci10b3VjaC9BbmxlaXR1bmdlbi9lY29tYW5hZ2VydG91Y2hfTW9kYnVzLVRDUC1SZWdpc3RyYXRpb24tZGF0YV9tYW51YWwucGRm/367149/0/Lng_YSxpM245S30zMTc4W2Y8cVRRXWlJVWRQJDsv?serialNumber=67215](url)

Added the correct markup with Sublime, basically a copy&paste job, but please review before implementing it.

Relatively new to github so not really familiar where to put this... but here we go:

"200": "Standby",
"201": "Ignition phase",
"202": "Pellet mode",
"203": "Required boiler temperature reached, lag",
"204": "Lag",
"205": "No request, lag",
"206": "Burner switched off",
"207": "Intermediate pellet store is empty, lag",
"208": "Heat exchanger cleaning is active",
"209": "Heat exchanger cleaning required, lag",
"210": "Power failure, lag",
"212": "Feed temperature too high, lag",
"216": "Burner switched off, lag",
"217": "Safety chain is open",
"218": "Safety chain is open, lag",
"219": "Residual oxygen content too high or too low, lag",
"220": "Flue gas temperature drop, lag",
"221": "Flue gas temperature is still greater than {RGT_Start}, standby",
"222": "Flue gas sensor is defective, standby",
"223": "Feed temperature too high, standby",
"224": "Lambda sensor is defective, lag",
"225": "Boiler temperature is sufficient, standby",
"226": "",
"227": "Boiler sensor is defective, standby",
"228": "Boiler sensor is defective, lag",
"229": "Lambda sensor is being heated",
"230": "Heat exchanger cleaning is waiting for a release, time",
"231": "Heat exchanger cleaning is waiting for a release, FGT",
"232": "Heat exchanger cleaning function is waiting for release, BT",
"233": "Suction system is waiting for release",
"234": "Intermediate pellet store is being filled",
"235": "Feed sensor short-circuit, standby",
"236": "Burn-back slide valve opens",
"237": "Boiler is being filled",
"238": "Lambda sensor is being calibrated",
"239": "Chimney sweep measurement release",
"240": "Alarm active!",
"241": "Close door! FGT and residual oxygen monitoring inactive",
"242": "Door has been open for too long, lag",
"243": "No burner release, time",
"244": "No burner time, lag",
"245": "Lambda sensor must be calibrated, lag",
"246": "Boiler cleaning",
"300": "Burner switched off, intermediate store is filling",
"301": "Log wood burning finished",
"302": "wait _s until feed is emptied!",
"303": "Ignite log wood manually",
"304": "Automatic log wood ignition",
"305": "Log wood",
"306": "Partial load of log wood, do not open door!",
"307": "Log wood, then pellets",
"308": "Log wood combustion stopped, do not open door!",
"309": "Door is open!",
"310": "Startphase",
"311": "Wood chip operation",
"312": "Feed blockage detected",
"313": "No feed motor current flow",
"314": "Direct extraction blockage detected",
"315": "No extraction motor current flow",
"316": "Automatic log wood function is waiting for the next time release",
"317": "Alarm! All outputs switched off!",
"318": "Door is open! A boiler start is not possible!",
"319": "Door is open! Close the door at the latest in _s!",
"320": "Operating fault, lag",
"321": "Position run of diverter for suction heads",
"322": "Boiler output test",
"323": "Suction head suction clearance active",
"324": "Shaker, manual",
"325": "Shaker is active",
"326": "Change of rotational direction",
"327": "No current flow M1 detected",
"328": "No current flow M1 detected",
"329": "Feed blockage detected",
"330": "No feed current flow detected",
"331": "No current flow M2 detected",
"332": "No current flow M2 detected",
"333": "External boiler active, lag",
"334": "External boiler active, standby",
"335": "Login: Administrator",
"336": "Login: Service technicians",
"337": "Login: Qualified personnel",
"338": "Chimney sweep measurement ended, lag",
"339": "Wait until the room air flap is open",
"340": "No burner release, outside temperature + forecast",
"341": "No burner release, outside temperature",
"342": "Buffer cylinder temperature adequate, standby",
"343": "Differential pressure switch triggered, lag",
"344": "HE-rinse condensing module active"

**Comment by LavermanJJ** [comment]
Didn't know, that there was a translation provided by Solarfocus. That's a great source for updating all the translations 👍 

You could create a Pull-Request, adding the translations yourself, or if you don't mind, I can also do it for you?

**Comment by tinerop** [comment]
I forked your project with my user, edited the file and created a pull request,... please let me know if i did it correctly...

**Comment by LavermanJJ** [comment]
That's how it's done! 🚀 Great Job!

**Comment by tinerop** [comment]
Thanks for your  feedback, - very excited to contribute and being a part of it!
