### ISSUE TITLE
Add new Biomass boiler registers from v22.090 and v23.010

### ISSUE THREAD

**Issue by LavermanJJ** [LavermanJJ/home-assistant-solarfocus#42]
Add sensors and a button for the following entities: 
https://github.com/LavermanJJ/pysolarfocus/blob/7f40d0df8b71c5666b8526cbbb9c239a045ad06b/pysolarfocus/components/pellets_boiler.py#L25-L34
```
       if api_version.greater_or_equal(ApiVersions.V_22_090.value):
            self.sweep_function_start_stop = DataValue(address=10,register_type=RegisterTypes.Holding)
            self.sweep_function_extend = DataValue(address=11,register_type=RegisterTypes.Holding)

        if api_version.greater_or_equal(ApiVersions.V_23_010.value):
            self.pellet_usage_last_fill = DataValue(address=14,count=2,multiplier=0.1)
            self.pellet_usage_total = DataValue(address=16,count=2,multiplier=0.1)
            self.heat_energy_total = DataValue(address=18,count=2,multiplier=0.1)            

            self.pellet_usage_reset = DataValue(address=12,register_type=RegisterTypes.Holding)
```

**Comment by LavermanJJ** [comment]
@lein1013 would you like to contribute the sensor part from your fork?

https://github.com/LavermanJJ/home-assistant-solarfocus/blob/8713c2e4580c34a1cfdd1277fcd5d24f2f0b1628/custom_components/solarfocus/sensor.py#L551-L572

**Comment by lein1013** [comment]
sure, I'll have a look to sync my fork. 
As I see its already inluded in the main branch. So a test with the latest version would be good - correct?

**Comment by LavermanJJ** [comment]
Great, thanks!

**Comment by lein1013** [comment]
@LavermanJJ I think the issue can be closed
