### ISSUE TITLE
Add contributor workflow documentation 

### ISSUE THREAD

**Issue by lein1013** [LavermanJJ/home-assistant-solarfocus#50]
As a new contributor is not easy to develop and test changed to the source. Hence some best practices would be great to support new developers. (I'll just sort my thoughts and I'm open for further recommendations)

e.g. 
1) small changes of enumerations can be directly done using the visual studio code addon and editing the related files in custom_components
2) test by reload home assistant
3) overtake changes the forked version and create a pull request

my recommendation is not to used the main branch of the forked repositore for pull requests. This main branch can be used to register the hacs integration in the own home assistant and use the update mechanism of hacs

maybe a dev container for the HA would also be maybe an option

Where could such documentation go? 
docs/CONTRIBUTE.md?

**Comment by LavermanJJ** [comment]
Great idea. It should be build upon/reference https://developers.home-assistant.io/docs/development_environment and https://developers.home-assistant.io/docs/creating_component_index for setting the stage/prerequisites. 

Location: I'd suggest to place it in root directory

Question: As there are many other custom components out there, it would be good to check if they have something and how they do it.

**Comment by LavermanJJ** [comment]
fixed by #52
