### ISSUE TITLE
[Feature Request]: Add API version info for Home Assistant

### ISSUE THREAD

**Issue by tinerop** [LavermanJJ/home-assistant-solarfocus#54]
Would be great to see the API Version (version of the "eco manager touch", in Home Assistant.
I have seen the "api_version": "Solarfocus API Version" in your code but don't know how to modify it so that it shows up in Home Assistant similar to a sensor.

The integration of my NUKI doorlock for instance solved this as a "sensor.nuki_bridge_firmware_version" with the "type: Diagnostic", in case that helps.

In the screenshot of the integration i see the current FW version, but I would like to display it in the GUI (lovelace) in Home Assistant.

![image](https://user-images.githubusercontent.com/130313096/233046107-8229f21d-be8d-47e1-ae65-2eb475a4e67e.png)

**Comment by tinerop** [comment]
I understand, - I finished reading the whole Modbus TCP document from Solarfocus... no FW there. 

Is this a hardware restriction from Solarfocus or could they provide the FW version through Modbus... by just assigning an address to it, basically the same way they provide info for a sensor... - I might later contact Solarfocus and ask them to implement some missing Modbus features from the community... long shot, but worth a try...

**Comment by LavermanJJ** [comment]
As ist is not supported by Solarfocus as of today, I'll close this issue for now. Once available, we can re-open this, or create a new one.
