### ISSUE TITLE
[Feature Request]: Add "Ecotop light" to device description

### ISSUE THREAD

**Issue by tinerop** [LavermanJJ/home-assistant-solarfocus#56]
The Screenshot of the integration says "Therminator von Solarfocus", in my case this should read  "EcoTop Light von Solarfocus", 
![image](https://user-images.githubusercontent.com/130313096/233048094-1772813d-c932-473e-afcf-60c9722e83d0.png)

I assume this could be accomplished by selecting the Solarfocus System during setup of the integration.
![image](https://user-images.githubusercontent.com/130313096/233053118-719790a2-9092-4ca9-82e2-7e3cf39a389c.png)

**Comment by LavermanJJ** [comment]
Will be done with #48

**Comment by LavermanJJ** [comment]
fixed
