### ISSUE TITLE
[Feature Request]: Add Enumertion for "biomass boiler status line" (all except therminator)

### ISSUE THREAD

**Issue by tinerop** [LavermanJJ/home-assistant-solarfocus#57]
I noticed that all other biomass-boilers (Kessel) except therminator need different enumeration to how the status line. 
Modbus TCP Address 2401 numbers 0-59.

Currently this value for "biomass boiler status line" is only working if you have a "therminator".

Possible solution:
Is it enough to add the numbers 0-59 to the existing numbers (200-344), because then i can add this and create a pull request...

or...an idea is when you choose at the setup between "therminator" and "all other biomass boilers" you could distinguish between the two different enumerations? but that's maybe not necessary...

referring to this:
![image](https://user-images.githubusercontent.com/130313096/233112592-19a6fb69-2801-413d-bd9e-f50b2a7d3a72.png)

and here is the modbus entry:
![image](https://user-images.githubusercontent.com/130313096/233113113-f086d63d-11ff-49c8-b364-37f6340636b2.png)

**Comment by LavermanJJ** [comment]
It'll be enough to add them as done with #49

**Comment by tinerop** [comment]
> It'll be enough to add them as done with #49

Thank you! Perfect!

**Comment by lein1013** [comment]
I think this issue could be closed  #49 was merged
