### ISSUE TITLE
[Feature Request]: Add sensor "biomass boiler message" corresponding to the sensor "biomass boiler message number"

### ISSUE THREAD

**Issue by tinerop** [LavermanJJ/home-assistant-solarfocus#59]
Currently:
we have a sensor "biomass boiler message number" that displays a plain number.

New Feature Proposal:
Would be great to have an additional sensor that displays the corresponding error message. Modbus doesn't provide this by default but it references the user manual of the biomass boiler.

Here is a list of the error message to each number for the ecotop light and ecotop zero.

1 Interner Speicher ist ungültig
3 Behältersensor möglicherweise verstaubt
5 Abgastemperatur zu gering
6 Abgasfühler unterbrochen
7 Abgasfühler falscher Messwert
9 Abgasfühler Kurzschluss
10 Werkseinstellungen wurden geladen
11 Fehler Drehzahlrückführung
12 Drehzahlrückführungs-Test
13 Drehzahlrückführung nicht OK
14 Maximale Saug-Laufzeit erreicht
16 Fehler Lambdasondenmessung
17 Fehler Kesselfühler
18 Kesseltemperatur ist zu hoch
19 Austragungsschnecke ist blockiert
20 Erster Zündversuch war erfolglos
23 Kommunikation zu Modul unterbrochen
24 Sicherheitskette hat ausgelöst
25 Stromausfall ist aufgetreten
26 Netzsicherung F3 defekt
27 Triacsicherung F6 defekt
30 Blockade Einschub
31 Wärmetauscher ist blockiert
32 Wärmetauscher ist blockiert
33 Kein Stromfluss Einschubmotor
35 CAN-Bus Unterbrechung
36 Sicherung am Frischwassermodul defekt 
37 Sicherung am Elektronikmodul (Solarmodul) defekt
38 Inbetriebnahme-Einstellungen wurdengeladen
40 Zündstörung Pellets/ Pelletsmangel?
41 Sicherung F1 oder F8 defekt
42 Pelletsmangel im Lagerraum
43 Fehler Saugsonden-Umschalteinheit
44 Kommunikationsfehler Kaskade
46 Die Aschebox ist voll und muss entleert werden
47 Wartung des Heizkessels empfohlen!
50 Kesseltüre ist offen!
51 Batterie im Bedienteil (Display) ist leer
52 Begrenzungsthermostat ist offen
67 Raumluftklappe öffnet nicht
68 Raumluftklappe schließt nicht
69 Fehler bei der Kommunikation mit dem Raumluftmodul
71 Kein Stromfluss Wärmetauscher
72 Hinweis: Kein Stromfluss Wärmetauscher
73 Fehler Referenzschalter Umschalteinheit
75 Raumfühler Zuweisung
76 Sicherheitstemperaturbegrenzer ausgelöst
77 Sicherung F12 defekt
78 Blockade Ascheaustragung
79 Kein Stromfluss Ascheaustragung
80 Differenzdruck - Kesselstopp
81 Elektrostatischer Staubabscheider offline
82 Differenzdruck - Saugturbine
83 Differenzdruck - Einschub
84 Warnung elektrostatischer Staubabscheider
85 Hochspannungskabel Staubabscheider
86 Notbetrieb Differenzdrucksensor
87 Differenzdruck - Kessel Sofortstopp

By default it shows number 0, we could translate this as "Keine Nachrichten derzeit".

Source: Handbook page 41:
[https://www.solarfocus.com/de/partnerportal/pdf/open/UGFydG5lcmJlcmVpY2gtREUvQmlvbWFzc2VoZWl6dW5nL2Vjb3RvcC16ZXJvLWxpZ2h0L0FubGVpdHVuZ2VuX1JlcG9ydF9lY290b3AtemwvZWNvdG9wLXplcm8tbGlnaHRfQmV0cmllYnNhbmxlaXR1bmcucGRm/297192/0/Lng_YSxpM245S30zMTc4W2Y8cVRRXWlJVWRQJDsv?serialNumber=67415](url)

**Comment by LavermanJJ** [comment]
To fix: add `pb_message_number` to strings.json, de.json and en.json similar to the other states.

**Comment by tinerop** [comment]
Thanks, I will try that and make a pull request... slowly learning...

**Comment by tinerop** [comment]
> To fix: add `pb_message_number` to strings.json, de.json and en.json similar to the other states.

I tried that with de.json made several pull request attempts and failed 5x at validation.. can't figure out why... can you please point me to my mistake?

**Comment by tinerop** [comment]
English version formatted for copypaste into en.json

"pb_message_number" : {
  "state" : {
    "1": "Internal memory is invalid",
    "3": "Container sensor possibly dusty",
    "5": "Flue gas temperature too low",
    "6": "Flue gas sensor interrupted",
    "7": "Flue gas sensor wrong measured value",
    "9": "Flue gas sensor short circuit",
    "10": "Factory settings loaded",
    "11": "Error speed feedback",
    "12": "Speed feedback test",
    "13": "Speed feedback not OK",
    "14": "Maximum suction time reached",
    "16": "Error lambda sensor measurement",
    "17": "Error boiler sensor",
    "18": "Boiler temperature is too high",
    "19": "Extraction auger is blocked",
    "20": "First ignition attempt failed",
    "21": "Triac filling auger defective",
    "22": "Triac output room extraction defective",
    "23": "Communication to electronic module interrupted",
    "24": "Safety chain has triggered",
    "25": "Power failure has occurred",
    "26": "Mains fuse F3 defective",
    "27": "Triac fuse F6 defective",
    "30": "Feed blockage",
    "31": "Heat exchanger is blocked",
    "32": "Heat exchanger is blocked",
    "33": "No feed motor current flow",
    "35": "CAN bus interruption",
    "36": "Fuse at fresh water module defective",
    "37": "A fuse in the electronic module (solarmodule) is defective",
    "38": "Commissioning settings loaded",
    "40": "Pellet ignition fault/pellet shortage?",
    "41": "Fuse F1 or F8 defective",
    "42": "Shortage of pellets in storage area",
    "43": "Fault in diverter for suction heads",
    "44": "Kommunikationsfehler Kaskade",
    "46": "The ash box is full and must be emptied",
    "47": "Maintenance of the boiler recommended!",
    "50": "Boiler door is open!",
    "51": "Display battery is dead",
    "52": "Limit thermostat is open",
    "67": "Room air flap does not open",
    "68": "Room air flap does not close",
    "69": "Communication error with room air module",
    "71": "No current flow heat exchanger",
    "72": "Note: No current flow heat exchanger",
    "73": "Fault in reference switch for suction heads",
    "75": "Room sensor assignment",
    "76": "Safety temperature limiter triggered",
    "77": "Fuse F12 is defective",
    "78": "Blockage of ash extraction",
    "79": "No current flow ash extraction",
    "80": "Differential pressure - Boiler stop",
    "81": "Electrostatic dust collector offline",
    "82": "Differential pressure - suction turbine",
    "83": "Differential pressure - insertion",
    "84": "Warning electrostatic dust collector",
    "85": "High voltage cable Dust collector",
    "86": "Emergency operation Differential pressure sensor",
    "87": "Differential pressure - Boiler immediate stop"
   },
}

**Comment by tinerop** [comment]
German Version for de.json ... not sure why the pull request doesn't validate.... any help appreciated...

"pb_message_number" : {
  "state" : {
    "1": "Interner Speicher ist ungültig",
    "3": "Behältersensor möglicherweise verstaubt",
    "5": "Abgastemperatur zu gering",
    "6": "Abgasfühler unterbrochen",
    "7": "Abgasfühler falscher Messwert",
    "9": "Abgasfühler Kurzschluss",
    "10": "Werkseinstellungen wurden geladen",
    "11": "Fehler Drehzahlrückführung",
    "12": "Drehzahlrückführungs-Test",
    "13": "Drehzahlrückführung nicht OK",
    "14": "Maximale Saug-Laufzeit erreicht",
    "16": "Fehler Lambdasondenmessung",
    "17": "Fehler Kesselfühler",
    "18": "Kesseltemperatur ist zu hoch",
    "19": "Austragungsschnecke ist blockiert",
    "20": "Erster Zündversuch war erfolglos",   
    "21": "Triac-Füllschnecke defekt"
    "22": "Triac-Ausgangsraumabsaugung defekt"
    "23": "Kommunikation zu Modul unterbrochen",
    "24": "Sicherheitskette hat ausgelöst",
    "25": "Stromausfall ist aufgetreten",
    "26": "Netzsicherung F3 defekt",
    "27": "Triacsicherung F6 defekt",
    "30": "Blockade Einschub",
    "31": "Wärmetauscher ist blockiert",
    "32": "Wärmetauscher ist blockiert",
    "33": "Kein Stromfluss Einschubmotor",
    "35": "CAN-Bus Unterbrechung",
    "36": "Sicherung am Frischwassermodul defekt",
    "37": "Sicherung am Elektronikmodul (Solarmodul) defekt",
    "38": "Inbetriebnahme-Einstellungen wurdengeladen",
    "40": "Zündstörung Pellets/ Pelletsmangel?",
    "41": "Sicherung F1 oder F8 defekt",
    "42": "Pelletsmangel im Lagerraum",
    "43": "Fehler Saugsonden-Umschalteinheit",
    "44": "Kommunikationsfehler Kaskade",
    "46": "Die Aschebox ist voll und muss entleert werden",
    "47": "Wartung des Heizkessels empfohlen!",
    "50": "Kesseltüre ist offen!",
    "51": "Batterie im Bedienteil (Display) ist leer",
    "52": "Begrenzungsthermostat ist offen",
    "67": "Raumluftklappe öffnet nicht",
    "68": "Raumluftklappe schließt nicht",
    "69": "Fehler bei der Kommunikation mit dem Raumluftmodul",
    "71": "Kein Stromfluss Wärmetauscher",
    "72": "Hinweis: Kein Stromfluss Wärmetauscher",
    "73": "Fehler Referenzschalter Umschalteinheit",
    "75": "Raumfühler Zuweisung",
    "76": "Sicherheitstemperaturbegrenzer ausgelöst",
    "77": "Sicherung F12 defekt",
    "78": "Blockade Ascheaustragung",
    "79": "Kein Stromfluss Ascheaustragung",
    "80": "Differenzdruck - Kesselstopp",
    "81": "Elektrostatischer Staubabscheider offline",
    "82": "Differenzdruck - Saugturbine",
    "83": "Differenzdruck - Einschub",
    "84": "Warnung elektrostatischer Staubabscheider",
    "85": "Hochspannungskabel Staubabscheider",
    "86": "Notbetrieb Differenzdrucksensor",
    "87": "Differenzdruck - Kessel Sofortstopp"
  },
}
