### ISSUE TITLE
[Bug]: Sensor "Biomass boiler cleaning" incorrectly shows value of "-1%"

### ISSUE THREAD

**Issue by tinerop** [LavermanJJ/home-assistant-solarfocus#60]
Sensor "Biomass boiler cleaning" incorrectly shows value of "-1%"
It should show something in between 0% – 100%  (bei spätestens 100% ist Kesselreinigung empfohlen) according to the Modbus Manual.

Similar to the "biomas boiler ash container".
![image](https://user-images.githubusercontent.com/130313096/233193290-7967e2d8-986b-4891-a48a-09a8f6f59528.png)

 - Home assistant version: [2023.4.4]  
 - Home assistant Supervisor:  [2023.04.0]
 - Home Assistant Operating System:  [9.5]
 - Solarfocus custom component version: [ 2.2.2 ]
 - Solarfocus firmware version: [22.050]
 - Solarfocus biomass boiler: [Ecotop light]
- Solarfocus boiler=buffer: [Hygiene Kombispecher HYKO]

**Comment by lein1013** [comment]
I've the same "-1%" value. 
I guess this value is not supported for ecotop light?!

**Comment by LavermanJJ** [comment]
I agree -1 seems to indicate that it is not supported
