### ISSUE TITLE
[Bug]: Sensor "biomass boiler outdoor temperature" shows wrong value

### ISSUE THREAD

**Issue by tinerop** [LavermanJJ/home-assistant-solarfocus#61]
Sensor "biomass boiler outdoor temperature" shows wrong value. Constant same temperature during the whole day, 10,3 C not changing.
On the ecotouch display it shows e.g. 8 C changing during the day.

Note: I do not have a room thermostat, just a Solarfocus outdoor temperature sensor that feeds data back to the biomass boiler for the heating curve. (Heizkurve).

 - Home assistant version: [2023.4.4]  
 - Home assistant Supervisor:  [2023.04.0]
 - Home Assistant Operating System:  [9.5]
 - Solarfocus custom component version: [ 2.2.2 ]
 - Solarfocus firmware version: [22.050]
 - Solarfocus biomass boiler: [Ecotop light]
 - Solarfocus boiler=buffer: [Hygiene Kombispecher HYKO]

**Comment by LavermanJJ** [comment]
@lein1013 can you confirm this bug?

**Comment by lein1013** [comment]
Outdoor temp looks good at my setup
I'm currently working on my fork of pysolarfocus - in my case the `boiler_operating_mode` shows something that is more like a temperature
Could be related to changes in the modbus registers that could happen in different firmware versions.

```
print(solarfocus.system)
print(solarfocus.pelletsboiler.boiler_operating_mode.value)
print(solarfocus.pelletsboiler.door_contact.value)
print(solarfocus.pelletsboiler.outdoor_temperature.value)
print(solarfocus.pelletsboiler.temperature.value)
Systems.EcoTop
334
1
157
341
```

**Comment by LavermanJJ** [comment]
As there has been no further update here, and the could not be reproduced, I'll close this issue.
