### ISSUE TITLE
[Bug]: "heating_circuit_1_target_supply_temperature" slider issue. 

### ISSUE THREAD

**Issue by tinerop** [LavermanJJ/home-assistant-solarfocus#62]
Issue: currently sensor shows after Installation "0 C" however when moving the slider to 10C and afterwards to the very left it says 7C. The sensor Shows 7C and cant be moved back to 0C. 

This seems odd...
however i dont even unverstand yet why it  starts with 7, i guess it's what Modbus says  but i dont understand the idea behind it.  

 - Home assistant version: [2023.4.4]  
 - Home assistant Supervisor:  [2023.04.0]
 - Home Assistant Operating System:  [9.5]
 - Solarfocus custom component version: [ 2.2.2 ]
 - Solarfocus firmware version: [22.050]
 - Solarfocus biomass boiler: [Ecotop light]
 - Solarfocus boiler=buffer: [Hygiene Kombispecher HYKO]

**Comment by LavermanJJ** [comment]
Fixed with version 3.0.0
This is due to the specification of Solarfocus. Valid values are 0,7-80, where 0 indicates that the temperature is calculated by Solarfocus according to the heating curve.
