### ISSUE TITLE
Is the development dead?

### ISSUE THREAD

**Issue by Vaszago** [LavermanJJ/home-assistant-solarfocus#69]
I see that there is no more development in this project. Has it been easily ended?

**Comment by LavermanJJ** [comment]
@Vaszago Nope, still alive. But as it sometimes goes, life comes in your way ;)

Next step planned is to release the beta. Before that some final testing is required to be sure migration works smoothly. 

Afterwards, #30 is on my list. But don't expect too much progress during the next month or so. 

As always in open source feel free to contribute to the project in any style or form :)

**Comment by Vaszago** [comment]
Thanks for the reply that it hasn't died yet. 
My programming skills are unfortunately not given that I can support you here. But what I like to do is test and point out any errors or improvements. 
But I've followed a lot of projects over the years, and it's always happened that developers have had projects die overnight. VU+ Sat Receiver as an example. 
Hence my question. 
But thank you for giving up your free time for us.

I know that you can set the support for photovoltaics in the service menu. I don't know if you can read and edit this data. I get one with Solaredge Inverter and this is specified as a support.

**Comment by LavermanJJ** [comment]
This integration supports reading/writing the photovoltaic registers. I would expect, that once you've integrated your Solarfocus heating with SolarEdge PV that meaningful values appear in these registers.

However, I wasn't able to test auch setup, as my PV is not natively supporter by Solarfocus. Therefore, I'm writing the values from my PV to Solarfocus using Home Assistant. 

With SolarEdge it seems you have both options:
- Directly connect Solarfocus with SolarEdge (assuming it is supported by Solarfocus)
- Integrate both in Home Assistant and broker the values from one to the other

**Comment by Vaszago** [comment]
Thanks for pointing out that the PV registers are being written. 
Will test it and let you know. 
Get the photovoltaic in October

**Comment by LavermanJJ** [comment]
@Vaszago I'll close the issue for now. Please feel free to add a new one any time.

**Comment by Vaszago** [comment]
Thank you for taking care of my request. The values are now transferred correctly again. Will open a new request if there are problems with the PV integration.
