### ISSUE TITLE
[Feature Request]: Missing buffer x35 temperature

### ISSUE THREAD

**Issue by b2m** [LavermanJJ/home-assistant-solarfocus#70]
I noticed that the home assistant integration is missing the x35 temperature in buffers.
It is provided by [pysolarfocus](https://github.com/LavermanJJ/pysolarfocus/blob/7f40d0df8b71c5666b8526cbbb9c239a045ad06b/pysolarfocus/components/buffer.py#L26) so adding it seems easy (and works like a charm).

So I am wondering whether this is just an oversight or by design?
Maybe because it might not be that easy to determine whether x35 is available when initializing the sensor entries?

**Comment by LavermanJJ** [comment]
Hi @b2m ,
No, I guess it simply hasn't been done yet. You are welcome to provide a PR to add it. Otherwise, I'll add it when I find time.
-Jeroen

**Comment by LavermanJJ** [comment]
duplicates #43

**Comment by b2m** [comment]
> @b2m fyi, [v3.1.0](https://github.com/LavermanJJ/home-assistant-solarfocus/releases/tag/v3.1.0) contains the requested sensors

That's awesome. Already updated and data collection continues as if nothing happend! 💯
