### ISSUE TITLE
Enumeration broken for Biomass boiler status after Update to v4

### ISSUE THREAD

**Issue by ragesoft** [LavermanJJ/home-assistant-solarfocus#81]
**Describe the bug**
I've got a New eco Manager Software Update during last checkup. 23.050
So i checked my hacs and Updated the integration, too. 
I select API Version 23.030
I had to change some entities in my homeassistant cuz of New naming... 
And during check i See the Biomass boiler status is now numeric again. IT was text last time i checked (i think) 

**Expected behavior**
Show Text instead of numeric values for this entity

**Screenshots**
![Screenshot_2023-09-19-17-06-46-675_io homeassistant companion android](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/3265070/6d66761e-d3ba-4be9-950a-6457e70feaf3)

**Desktop (please complete the following information):**
 - Home assistant version: [e.g. 2023.4.1]: 203.8.1
 - Solarfocus custom component version [e.g. 3.0.0]:4.0.2
 - Solarfocus firmware version [e.g. 23.020]:23.050

Thx for help and keeping this nice Integration alive.

**Comment by LavermanJJ** [comment]
I'll check

**Comment by LavermanJJ** [comment]
Released in v4.0.3
