### ISSUE TITLE
Setting the temperature of the buffer tank

### ISSUE THREAD

**Issue by Vaszago** [LavermanJJ/home-assistant-solarfocus#83]
Is there a way to adjust the temperatures of the buffer tank. 
Just like the temperature of the boiler with a slider. So that I can increase the temperature below when the electricity price is cheapest for 3 hours, or PV overproduction, in order to get the excess energy into the heating system. 
I have a setting under PV.

It would be great if I could set the value with a automation.

![image](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/66181893/1bcda08c-9d54-4df6-9ea5-2ede786b4e6a)

**Comment by LavermanJJ** [comment]
Hi @Vaszago - I certainly would love to be able to set these two variables via this integration. Unfortunately, Solarfocus does not expose them via Modus. If you want, you can write them an email to ask If they could do so in future.

**Comment by Vaszago** [comment]
<img width="634" alt="image" src="https://github.com/LavermanJJ/home-assistant-solarfocus/assets/66181893/13ec5cab-6d5a-4a43-b331-acfa74a2d107">

Here it says something that the buffer values can be adjusted externally. But it won't work via Modbus.
