### ISSUE TITLE
Simulate PV surplus

### ISSUE THREAD

**Issue by Vaszago** [LavermanJJ/home-assistant-solarfocus#84]
Hi

I now own a PV with Solaredge WR. And I can set the heat pump so that from a PV surplus feed-in of 2000W, the flow temperatures of the heating circuits and the buffer tank are raised by an adjustable value. This works via Modbus. Is it possible to create an entity to simulate a PV surplus with an automation? Then you could get the WP at the 3 cheapest hours of electricity cheaper energy in the WP to optimize the electricity costs a bit.  

<img width="399" alt="image" src="https://github.com/LavermanJJ/home-assistant-solarfocus/assets/66181893/190a4527-ddbb-475c-822a-61eb8e40e4b8">

<img width="397" alt="image" src="https://github.com/LavermanJJ/home-assistant-solarfocus/assets/66181893/bb6c917b-1b80-4d59-a451-fe051fff9abf">
[vampair_PV-Eigenverbrauchsoptimierung_Anleitung.pdf](https://github.com/LavermanJJ/home-assistant-solarfocus/files/12837373/vampair_PV-Eigenverbrauchsoptimierung_Anleitung.pdf)

**Comment by Vaszago** [comment]
Hi
Have you ever looked at whether it could be done?

**Comment by LavermanJJ** [comment]
Hi @Vaszago , I'm not sure if I get you question correctly. Your goal is to trigger the heat pump to run and charge the boiler and/or buffer. If that is the case, you can utilize the SmartGrid functionality. Setting it to "Request Operation" triggers the heat pump to charge boiler and/or buffer according to the "Überstromnutzung" settings.

**Comment by Vaszago** [comment]
Hi
I didn't think it would be so easy. I'll try it tomorrow to see if the HP behaves like it does when using overcurrent. That would be great. Then I can tell the WP to charge the WP with the 3 cheapest hours of electricity. I'll let you know if it works.

**Comment by Vaszago** [comment]
I tried it and it works. 
Is there a way to display the grid status?

**Comment by LavermanJJ** [comment]
You mean other than adding it to a home assistant dashboard?

**Comment by Vaszago** [comment]
Hello

I can change the Smart Grid value in your integration. It is working. But I don't get any feedback when the WP automatically changes the value to switch on.
Or did I miss something.
I would use the feedback to control the thermostats on the radiators to increase the temperature.

**Comment by LavermanJJ** [comment]
I see. You are right this information is currently not directly exposed by Solarfocus. However, in my installation the boiler target temperature increases, when excess energy is present, by that I could identify it. Is this similar for you?
... it's more a workaround 😉

**Comment by Vaszago** [comment]
I'm still tinkering with the workarond. But it still doesn't work satisfactorily.

**Comment by Vaszago** [comment]
I think the topic can be closed
