### ISSUE TITLE
integration not working with HA 2024.01

### ISSUE THREAD

**Issue by LavermanJJ** [LavermanJJ/home-assistant-solarfocus#89]
**Describe the bug**
Integration fails to load after upgrading to 2024.01

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Home assistant version: [e.g. 2023.4.1]:
 - Solarfocus custom component version [e.g. 3.0.0]:
 - Solarfocus firmware version [e.g. 23.020]:

**Additional context**
TODO Investigate ...

**Comment by Vaszago** [comment]
Can confirm the error. Integration is not loading. Here are a few logs and infos.
If you still need information, let me know


<img width="455" alt="image" src="https://github.com/LavermanJJ/home-assistant-solarfocus/assets/66181893/bcab951e-14bc-4677-bca5-d7c7e67ef660">

Solarfocus V4.03
Firmware 21.140


[home-assistant_2024-01-04T08-25-35.369Z Solarfocus.log](https://github.com/LavermanJJ/home-assistant-solarfocus/files/13827795/home-assistant_2024-01-04T08-25-35.369Z.Solarfocus.log)



Logger: homeassistant.loader
Source: loader.py:842
First occurred: 09:23:35 (21 occurrences)
Last logged: 09:23:36

Unexpected exception importing platform custom_components.solarfocus.number
Unexpected exception importing platform custom_components.solarfocus.button
Unexpected exception importing platform custom_components.solarfocus.binary_sensor
Unexpected exception importing platform custom_components.solarfocus.water_heater
Unexpected exception importing platform custom_components.solarfocus.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/solarfocus/sensor.py", line 189, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'supported_systems' follows default argument



Logger: homeassistant.setup
Source: setup.py:403
First occurred: 09:23:35 (21 occurrences)
Last logged: 09:23:36

Unable to prepare setup for platform 'solarfocus.number': Platform not found (Exception importing custom_components.solarfocus.number).
Unable to prepare setup for platform 'solarfocus.button': Platform not found (Exception importing custom_components.solarfocus.button).
Unable to prepare setup for platform 'solarfocus.binary_sensor': Platform not found (Exception importing custom_components.solarfocus.binary_sensor).
Unable to prepare setup for platform 'solarfocus.water_heater': Platform not found (Exception importing custom_components.solarfocus.water_heater).
Unable to prepare setup for platform 'solarfocus.climate': Platform not found (Exception importing custom_components.solarfocus.climate).

**Comment by Vaszago** [comment]
Another log
[Log Solarfocus.txt](https://github.com/LavermanJJ/home-assistant-solarfocus/files/13827910/Log.Solarfocus.txt)

**Comment by LavermanJJ** [comment]
Identified the issue and working on a solution

**Comment by RobertoCravallo** [comment]
Cool, so no need for more feedback? Thank you for this very appreciated tool!!!!

**Comment by Vaszago** [comment]
Sonoff with a simular problem

https://github.com/AlexxIT/SonoffLAN/issues/1288

**Comment by LavermanJJ** [comment]
As far as I understand, the issue is related to https://developers.home-assistant.io/blog/2023/12/11/entity-description-changes/ . Due to these changes, the `supported_systems` list is not recognized as having a default argument
cf. https://github.com/LavermanJJ/home-assistant-solarfocus/blob/89e3c8b500a8bfa277c78f4a49819cbda59448fd/custom_components/solarfocus/entity.py#L30-L32

Leading to the following error:
```
TypeError: non-default argument 'supported_systems' follows default argument
```

I've tried different things, but cannot get it to work. :upside_down_face: ... will continue tomorrow. If there is anyone who is more into Dataclasses etc - help is always welcome 😃

**Comment by RobertoCravallo** [comment]
> I've tried different things, but cannot get it to work. 🙃 ... will continue tomorrow. If there is anyone who is more into Dataclasses etc - help is always welcome 😃

Thank you for your troubles. I would really like to help, but have absolutely to knowledge that would be helpful!!!!

**Comment by RobertoCravallo** [comment]
Any (good) news?

**Comment by LavermanJJ** [comment]
Unfortunately not. I was hoping that with 2024.01.01 or .02 something would be fixed on HA side but that's not the case, so I'm left with finding a workaround, as I cannot get it to work the way it did before.

**Comment by LavermanJJ** [comment]
I just upgraded, and "works on my machine" 😄 ... let me know if you experience any issues.

**Comment by RobertoCravallo** [comment]
Looks good to me, your workaround. Got a bit confused bei outside temp. "0,30", till I realized, that is how cold it is...  ;-)

Thank you very, very much!!!

Robert from Mannheim, Germany

**Comment by Vaszago** [comment]
Thanks, the workaround helped and the integration works again. Thank you
