### ISSUE TITLE
Ecotop Light 23.010 Biomas boiler state not enumerated

### ISSUE THREAD

**Issue by lein1013** [LavermanJJ/home-assistant-solarfocus#93]
**Describe the bug**
Missing enumeration of States "Solarfocus Boiler boiler status" - shows "0" instead of "Bereitschaft"

**Expected behavior**
Numbers shall be enumerated

**Desktop (please complete the following information):**
 - Home assistant version: [e.g. 2023.4.1]:  2024.2.1
 - Solarfocus custom component version [e.g. 3.0.0]:  4.0.4
 - Solarfocus firmware version [e.g. 23.020]: 23.010

**Additional context**
Root cause is that for EcoTop Light at least for this verison the enum starts at 0

adding this to strings.json (de.json, en.json) fixes this
```
      "bb_status" : {
        "state" : {
          "0": "Bereitschaft",
          "1": "Zündphase",
...
```
fom the ecomanger-touch_Modbus pdf
![image](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/72338417/94c6ad97-be5f-46e4-925b-24573144a9bb)

**Comment by lein1013** [comment]
de are available -> only default and en are missing
will be closed by https://github.com/LavermanJJ/home-assistant-solarfocus/pull/94

**Comment by lein1013** [comment]
Adding the Mod bus register description (german) I just got from Solarfocus (with permission to share on github)
[EcoMT_Modbus-TCP_Anleitung_v11-231212_DE.pdf](https://github.com/LavermanJJ/home-assistant-solarfocus/files/14288672/EcoMT_Modbus-TCP_Anleitung_v11-231212_DE.pdf)
it includes information about registers and at which version they are available

**Comment by LavermanJJ** [comment]
That's great! I'll take this information to extend the integration accordingly.
