### ISSUE TITLE
Integration won't load

### ISSUE THREAD

**Issue by Alex-joomla** [LavermanJJ/home-assistant-solarfocus#96]
**Describe the bug**
Integration won't load with the latest HA Version 2024.2.1.

**Desktop (please complete the following information):**
 - Home assistant version: [2024.2.1]:
 - Solarfocus custom component version [e.g. v4.0.4]:

**Additional context**

<img width="1126" alt="Bildschirmfoto 2024-02-11 um 22 10 33" src="https://github.com/LavermanJJ/home-assistant-solarfocus/assets/32268233/f488fc44-0525-4315-b1b3-8efb6774fca4">
m here.

**Comment by lein1013** [comment]
Which device and firmware version do you have? Which configuration (boiler, water, ...)?
It could be that you have a version where the register 1100 can not be read

**Comment by Alex-joomla** [comment]
Hi! I’m on Ecomanager V23.010
Boiler is a Octoplus with no internal water pocket

**Comment by Alex-joomla** [comment]
Additional Information: I read all relevant Data with the standard Modbus integration and this work flawlessly. I had it all setup before your integration was created and so I left it there for backup :-)

**Comment by LavermanJJ** [comment]
Are you running on Home-Assistant OS, Supervised, or else? And did you try the latest release? https://github.com/LavermanJJ/home-assistant-solarfocus/releases/tag/v4.1.0

**Comment by LavermanJJ** [comment]
I'm closing this issue, as it seems to be stale. Please re-open if required.
