### ISSUE TITLE
SOLARFOCUS breaks my HA 

### ISSUE THREAD

**Issue by RobertoCravallo** [LavermanJJ/home-assistant-solarfocus#99]
**Describe the bug**
I was searching for weeks for this. So today I installed a new HA VM in PROXMOX and just started adding integrations to try and see when it breaks!!! Success!!!!

As soon as I add the SOLARFOCUS integration, it breaks RADIO Browser!! Tankerkönig, GARMIN and LG ThinQ get broken in my regular installation and where not as yet added to this instance.

I remember you writing about a "workaround" for HA 2024.x.x. But that can not be the actual problem, because the rror occurred right after the installation of 2024.x.x. So the problem lies deeper I guess. I think you might be installing the wrong version of Python.

Another interesting effect. Installed a new HA via script in PROXMOX and then installed my backup. Everything was fine and I was happy. Until I booted HA. Then the error is back right away. So I am assuming, that installing the back-up overwrites functional code in HA, but everything seems fine until HA is restarted!!!

**To Reproduce**
1. install SOLARFOCUS via HACS
2. Add the entity
3. IMPORTANT!!! Restart HA. There is no problem after the configuration, until HA restarts!! 

**Expected behavior**
Other integrations should continue to work properly and no more server 500 errors

**Screenshots**
![305651760-a556c587-3def-471e-ab9b-812585219fea](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/112649622/c2e47d02-8af8-4c50-b2c2-6871b33db445)
![305651771-0984c4eb-3007-4dca-a97b-34afe5f32c73](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/112649622/0d533620-dd5c-462d-bdde-889314b6c296)
![305651795-96c6eb4f-9f72-4b2a-823b-27c08b933189](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/112649622/5adf7972-0d7b-42aa-9e96-7a257a90b1df)

**Desktop (please complete the following information):**
 - Home assistant version: 2024.2.2
 - Solarfocus custom component version 4.0.4
 - Solarfocus firmware version v 21.140

**Additional context**
SOLARFOCUS works fine, but breaks other integrations. Below text from the developer of the GARMIN integration, which I suspected first. 

As far as I can tell, the problem is related to Python 3.12 and SOLARFOCUS seems to install an older library.

"There are several of these breaking errors in the log, for multiple packages, with the result that the needed underlaying libraries cannot be installed and the integration(s) fail to install.
[AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?](https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean)

If you google that those errors are related to Python 3.12 (which 2024 is started to use) this should not be an issue with Garmin, or most other integrations, but it could be that one or more of them (or backup/ha itself) installs an older version of a tools called setuptools. This may cause these issues, so HA needs to be completely uptodate and no integration may downgrade setuptools or other python setup ralated tools. I know this issue was present and fixed in older builds of HA, but maybe there is still a bug hidden somewhere. "

**Comment by RobertoCravallo** [comment]
[home-assistant_solarfocus_2024-02-19T09-09-09.369Z.log](https://github.com/LavermanJJ/home-assistant-solarfocus/files/14328923/home-assistant_solarfocus_2024-02-19T09-09-09.369Z.log)

**Comment by mleck28** [comment]
Hello, I can confirm the behavior. The Radio.Browser and Yamaha's MusicCast are also not working for me anymore. Attached are the error messages.
![HA_Solarfocus_2024-02-19b](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/160210695/1359deff-c345-4b38-b456-460eb1de1381)
![HA_Solarfocus_2024-02-19a](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/160210695/9c30aace-a8ab-469f-8638-74a2c591dc68)

**Comment by LavermanJJ** [comment]
Thanks for reporting - I can confirm that I have a similar issue with another integration. I'll look into it

**Comment by RobertoCravallo** [comment]
I just installed a new HA VM under PROXMOX. From my running system I deinstalled SOLARFOCUS and made a back-up. Installed the back-up in the new VM HA and everything is fine. So I am very sure the problem lies with SOLARFOCUS.

Thank you for your troubles. Hope you find the problem soon!!!

**Comment by LavermanJJ** [comment]
Thanks for debugging and isolating the problem

**Comment by RobertoCravallo** [comment]
No problem. This was a pain in the you know where, since the first 2024.x update.

Regards from Mannheim, Germany

**Comment by LavermanJJ** [comment]
@RobertoCravallo would you be able to test the 4.1.0 release, if it fixes the issue for you? https://github.com/LavermanJJ/home-assistant-solarfocus/releases/tag/v4.1.0

**Comment by RobertoCravallo** [comment]
I can check tomorrow. Regards

**Comment by LavermanJJ** [comment]
@mleck28 Can you also confirm? If so, I'd resolve the issue afterwards.

**Comment by RobertoCravallo** [comment]
War eben im Keller und habe mal die Tür meines Gerätes auf und zu gemacht. No change...

**Comment by mleck28** [comment]
> @mleck28 Can you also confirm? If so, I'd resolve the issue afterwards.

Ich kann die fehlerhaften "Integrationen" nicht löschen / I cannot delete the faulty 'integrations'.

**Comment by RobertoCravallo** [comment]
Geht es jetzt um YAMAHA? Das kannst Du lassen, wird wohl wieder funktionieren, wenn Du SOLARFOCUS neu einspielst.

![Einstellungen – Home Assistant 2024-02-22 15-19-18](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/112649622/f7298677-77a4-456f-aa1d-e94efe7c2335)
Zuerst das Teil löschen und dann unter HACS. Neu starten und bei HACS / SOLF dann BETA-Versionen erlauben und die 4.1.0 installieren. 
![HACS – Home Assistant 2024-02-22 15-21-35](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/112649622/efa70686-7db2-424d-9c8d-b3146984e046)
Danach lief es bei mir wieder. Nach Installation / Konfiguration der Integration HA neu starten.

**Comment by mleck28** [comment]
Vielen Dank für den Hinweis. Bei mir kam automatisch ein Update. Habe aber Solarfocus nun deinstalliert und wieder neu installiert und eingerichtet. Habe nach mehrmaligen Neustarts von HA auch den PI neu gestartet. Bei mir ist der Fehler leider immernoch da:
![HA_Yamaha_2024-02-22c](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/160210695/ec22f4f4-064d-4fc0-a0e4-0c57d2b91c7d)
![HA_Yamaha_2024-02-22b](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/160210695/9448daad-34ee-4e99-a557-49baae2ed54d)

**Comment by RobertoCravallo** [comment]
Bin mit PROXMOX unterwegs und kenne mich mit den RASPBERRY nicht aus. 

Hast Du YAMAHA mal deinstalliert?

An den lieben [LavermanJJ](https://github.com/LavermanJJ), die "Tür" ist noch immer offen!  ;-)

**Comment by mleck28** [comment]
Ich kann beides leider nicht deinstallieren. Ich kann zwar den Knopf drücken, aber da passiert nichts. Das ist die Fehlermeldung, die beim Löschen auftritt.
![HA_Yamaha_2024-02-22d](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/160210695/daab0578-8d8f-4060-9121-7e5df90788ab)

**Comment by RobertoCravallo** [comment]
![Entwicklerwerkzeuge – Home Assistant 2024-02-22 17-29-13](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/112649622/4de7a0a9-8421-4e14-b7c3-a94bedd227b0)
Du hast HA also so gestartet, richtig? Wenn Du SOLARFOCUS deinstalliert hast, hast Du dann mal versucht YAMAHA los zu werden. **Bevor** Du SoFo wieder installierts.

**Comment by mleck28** [comment]
Das habe ich gemacht und nun auch zur Kontrolle noch einmal.
- Solarfocus gelöscht und dann deinstalliert.
- Start in den abgesicherten Modus.
- Versucht die fehlerhaften Integrationen zu löschen. ==> Leider erfolglos :-(
Hier die Fehlermeldungen seit dem Neustart in den abgesicherten Modus:
![HA_Yamaha_2024-02-22f](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/160210695/b0c5f256-a6b2-4c76-8568-41e6b81b5c1c)

Gibt es mit der Konsole bzw. Terminal noch ne Möglichkeit diese beiden Integrationen zu löschen?

**Comment by RobertoCravallo** [comment]
Sorry, da bin ich jetzt leider raus...

**Comment by LavermanJJ** [comment]
You need to access to /config folder of home-assistant (e.g. via the visual studio code add-on) and browse to custom_components. There you'll find the folder of the integration. Now remove that and restart the overall system. That's how it worked for me.
